- pipeline: "Deployment"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/main"
  fail_on_prepare_env_warning: true
  resources: "X2LARGE"
  actions:
  - action: "Build multi-arch Docker image"
    type: "DOCKER_BUILD_MULTI_ARCH"
    dockerfile_path: ""
  - action: "Build Docker image"
    type: "DOCKERFILE"
    context_path: "Buddy docker/"
    do_not_prune_images: true
    ignore_errors: true
    provenance: "MIN"
