- pipeline: "Deployment"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/main"
  fail_on_prepare_env_warning: true
  resources: "X2LARGE"
  actions:
  - action: "Build multi-arch Docker image"
    type: "DOCKER_BUILD_MULTI_ARCH"
    dockerfile_path: ""
  - action: "Run Docker Container"
    type: "RUN_DOCKER_CONTAINER"
    docker_image_name: "docker/dockerfile"
    docker_image_tag: "v1"
    export_container_path: "/"
    mount_filesystem_disable: true
    volume_mappings: []
  - action: "Push Docker image"
    type: "DOCKER_PUSH"
    integration: "Docker_Hub"
    docker_image_tag: "version-number"
    docker_registry: "DOCKER_HUB"
    repository: "friendgamer99/example"
    ignore_errors: true
  - action: "Build Docker image"
    type: "DOCKERFILE"
    context_path: "Buddy docker/"
    do_not_prune_images: true
    ignore_errors: true
    provenance: "MIN"
  - action: "jekyll build"
    type: "BUILD"
    docker_image_name: "jekyll/jekyll"
    docker_image_tag: "4.3.3"
    execute_commands:
    - "jekyll build"
    volume_mappings:
    - "/:/srv/jekyll"
    ignore_errors: true
    shell: "BASH"
